# 1. 
trigger:
  branches:
    exclude:
    - feature/1
    - feature/2 
    include:
     - main
  # tags:
  #  exclude:
  #  include:
  batch: true 
  paths:
   exclude:
   include:
     - 
# 2. 

pool:
 demands:
 name: 
 vmImage: 

 #3 parameters:


parameters:
- name: dev # Required as first property.
  displayName: string # Human-readable name for the parameter.
  type: string
  default: string | parameters | [ parameters ] # Default value; if no default, then the parameter MUST be given by the user at runtime.
  values: [ string ] # Allowed list of values (for some data types).

- name: runTests
  type: boolean
  default: true

- name: appName
  type: string
  default: myApp

steps:
- script: echo Deploying ${{ parameters.appName }} to ${{ parameters.environment }}

#4. Variable 

variables:      # pipeline-level
  MY_VAR: 'my value'
  ANOTHER_VAR: 'another value'

stages:
- stage: Build
  variables:    # stage-level
    STAGE_VAR: 'that happened'

  jobs:
  - job: FirstJob
    variables:  # job-level
      JOB_VAR: 'a job var'
    steps:
    - script: echo $(MY_VAR) $(STAGE_VAR) $(JOB_VAR)

#5. variable group 

variables:
- group: tcs