trigger: 
  - main
  
pool: Mera-pool
parameters:
- name: Environemnt
  displayName: Select Environment 
  type: string
  default: dev
  values: 
    - dev
    - tst


stages:
- stage: 
  displayName: Plan
  jobs:
    - job: 
      steps: 
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(workdir)'
          backendAzureRmUseCliFlagsForAuthentication: true
          backendAzureRmUseIdTokenGeneration: true
          backendServiceArm: 'ser2'
          backendAzureRmStorageAccountName: 'backendstorage9454'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform-$(Environment).tfstate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(workdir)'
          backendAzureRmUseCliFlagsForAuthentication: true
          backendAzureRmUseIdTokenGeneration: true
          environmentServiceNameAzureRM: 'ser2'
          environmentAzureRmUseIdTokenGeneration: true
      
- stage: 
  displayName: Scanning
  jobs:
    - job: 
      displayName: tflint scanning
      steps:
      - task: tfsec@1
        inputs:
          version: 'v1.26.0'

- stage: 
  displayName: Deploy
  jobs:
    - job: Terraformplan
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(workdir)'
          backendAzureRmUseCliFlagsForAuthentication: true
          backendAzureRmUseIdTokenGeneration: true
          backendServiceArm: 'ser2'
          backendAzureRmStorageAccountName: 'backendstorage9454'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform-$(Environment).tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(workdir)'
          environmentServiceNameAzureRM: 'ser2'
          backendAzureRmUseCliFlagsForAuthentication: true
          backendAzureRmUseIdTokenGeneration: true
          environmentAzureRmUseIdTokenGeneration: true
      
    - job: ManualValidation
      pool: server
      dependsOn: Terraformplan
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'sauravtripathi23@gmail.com'

    - job: Apply
      dependsOn:  ManualValidation
      steps:

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(workdir)'
          backendAzureRmUseCliFlagsForAuthentication: true
          backendAzureRmUseIdTokenGeneration: true
          backendServiceArm: 'ser2'
          backendAzureRmStorageAccountName: 'backendstorage9454'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform-$(Environment).tfstate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(workdir)'
          environmentServiceNameAzureRM: 'ser2'
          backendAzureRmUseCliFlagsForAuthentication: true
          backendAzureRmUseIdTokenGeneration: true
          environmentAzureRmUseIdTokenGeneration: true


          
      
        
